apiVersion: v1
kind: Service
metadata:
  name: my-svc
  namespace: default
  annotations:
    haproxy.org/pod-maxconn: "1"
    haproxy.org/load-balance: "leastconn"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4242
  selector:
    training.kubeflow.org/job-role: launcher
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  ingressClassName: haproxy
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-svc
            port:
              number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-ingress
  namespace: haproxy-controller
data:
  timeout-server: 10m
  timeout-connect: 1m
  timeout-queue: 1h
  timeout-http-request: 1m
  syslog-server: "address:stdout, format:raw, facility:daemon"
  auth-type: basic-auth
  auth-secret: haproxy-controller/haproxy-credentials