name: shared-mem-test

on:
  push:
    branches:
      - 'sharedmem'

jobs:

  test:
    runs-on: ubuntu-latest
    container: 
      image: ubuntu:latest
      options: --ipc=host

    services:
      model:
        image: linusseelinger/model-exahype-tsunami
        ports:
        - 4242:4242
        options: --ipc=host

    steps:
       -
        name: Checkout
        uses: actions/checkout@v2
       -
        name: Dependencies
        run: |
          apt update; DEBIAN_FRONTEND="noninteractive" apt install -y g++ libssl-dev
       -
        name: Build and run
        run: |
          cd clients/c++ && ./build.sh && ./http-client model:4242
